Author:  Joe Graham
E-mail:  joe.w.graham@gmail.com
Project: Embedded Ensemble Encoding (EEE) Theory
Drive:   https://drive.google.com/drive/folders/0Bx7OIVIgY3AVU2pKQ21EdFVPVDA

* 2019-01-10 -- Cleaning up and organizing

In progress
-----------
Uninstall Anaconda
Reinstall Anaconda (Python 2 and 3)
Uninstall NEURON
Install latest NEURON
Install Visual Studio Code
Run Sergio's EEE network sim
Summarize current network model
Prepare for discussion with EEE team
Meeting 10am Eastern to discuss network

** Anaconda

*** Uninstalling 

https://docs.anaconda.com/anaconda/install/uninstall/

anaconda-clean doesn't install properly:

	graham-mac% conda install anaconda-clean
	Fatal Python error: initfsencoding: unable to load the file system codec
	  File "/Users/graham/anaconda/lib/python2.7/encodings/__init__.py", line 123
	    raise CodecRegistryError,\
	                            ^
	SyntaxError: invalid syntax

	Current thread 0x0000000111f705c0 (most recent call first):
	Abort
	Fatal Python error: initfsencoding: unable to load the file system codec
	  File "/Users/graham/anaconda/lib/python2.7/encodings/__init__.py", line 123
	    raise CodecRegistryError,\
	                            ^
	SyntaxError: invalid syntax

	Current thread 0x0000000107f365c0 (most recent call first):
	Abort
	graham-mac% 

Seems like it may already be installed.  Just going to run it:

	graham-mac% anaconda-clean
	Delete .anaconda? (Y or N): y
	Delete .bash_profile? (Y or N): n
	Delete .bash_profile-anaconda.bak? (Y or N): n
	Delete .cache? (Y or N): n
	Delete .conda? (Y or N): y
	Delete .condarc? (Y or N): y
	Delete .config? (Y or N): n
	Delete .continuum? (Y or N): y
	Delete .ipynb_checkpoints? (Y or N): y
	Delete .ipython? (Y or N): y
	Delete .jupyter? (Y or N): y
	Delete .matplotlib? (Y or N): y
	graham-mac% 

Now to delete old anaconda dirs:

	/anaconda3
	/Users/graham/anaconda

*** Reinstalling Anaconda

**** To install Python 2 and 3:

http://docs.anaconda.com/anaconda/install/mac-os/#macos-graphical-install
https://conda.io/docs/user-guide/tasks/manage-python.html

Installing Anaconda3, comes with Visual Studio

Having a problem with: "conda search python" and "ipython". 
Switching Terminal to Bash.  Now it works fine.

So far I only have Python 3 installed.  Will try to run network sims in 
Python 3 before bothering with installing 2.7

*** To use Python 2 and 3:

https://docs.anaconda.com/anaconda/user-guide/tasks/switch-environment/

Going to try with just Python 3 for now.

** NEURON

Uninstalling and reinstalling NEURON.

Moving /Applications/NEURON-7.5 to the Desktop (will delete once everything
is working

Getting latest copy of NEURON
https://www.neuron.yale.edu/neuron/download

Running gui installer.  Seems to have worked: can run programs from Finder,
but not from command line.

Looking at path:
	graham$ echo $PATH
	/Users/graham/anaconda3/bin:/usr/site/nrniv/local/python/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/graham/anaconda/bin:/Applications/NEURON-7.4/nrn/x86_64/bin://anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/opt/X11/bin

Okay, my new NEURON is in NEURON-7.6, not NEURON-7.4
Need to update my PATH

https://hathaway.cc/2008/06/how-to-edit-your-path-environment-variables-on-mac/

Editing .bash_profile, changing all 7.4 to 7.6

Now NEURON commands run from command line.


** EEE Network Sims

*** Updating repo:
https://github.com/Neurosim-lab/EEE_network

	graham$ git clone https://github.com/Neurosim-lab/EEE_network.git
	graham$ cd EEE_network/mod/
	graham$ nrnivmodl

Looks good except for ghk.inc:

	Translating NMDAeee.mod into NMDAeee.c
	"/Applications/NEURON-7.6/nrn/x86_64/bin/nocmodl" PlateauConductance
	Couldn't open: ghk.inc
	Couldn't open ghk.inc
	make: *** [NMDAeee.lo] Error 1

Looks like there is no ghk.inc in the mod dir...

	graham$ git clone https://github.com/Neurosim-lab/EEE_network.git
	graham$ cd EEE_network/mod/
	graham$ cp /usr/site/nrniv/local/mod/ghk.inc ./ghk.inc
	graham$ nrnivmodl

Now it seems to have worked fine.  
Will add ghk.inc to the git repo.

But first, I notice I need to merge Salvador's improvements from his
'simplify' branch to the Master... done.

Starting over.

	graham$ rm -rf EEE_network/
	graham$ git clone https://github.com/Neurosim-lab/EEE_network.git
	graham$ cd EEE_network/mod/
	graham$ nrnivmodl

Still has the ghk.inc problem.  Will add to repo.

	graham$ cd ~
	graham$ rm -rf EEE_network/
	graham$ git clone https://github.com/Neurosim-lab/EEE_network.git
	graham$ cd EEE_network/mod/
	graham$ cp /usr/site/nrniv/local/mod/ghk.inc ./ghk.inc
	graham$ git status
	On branch master
	Your branch is up to date with 'origin/master'.

	Untracked files:
	  (use "git add <file>..." to include in what will be committed)

		ghk.inc

	nothing added to commit but untracked files present (use "git add" to track)
	graham$ git add ghk.inc 
	graham$ git status
	On branch master
	Your branch is up to date with 'origin/master'.

	Changes to be committed:
	  (use "git reset HEAD <file>..." to unstage)

		new file:   ghk.inc

	graham$ git commit -m "Added ghk.inc which is needed by NMDAeee.mod"
	[master 5fb1177] Added ghk.inc which is needed by NMDAeee.mod
	 1 file changed, 35 insertions(+)
	 create mode 100644 mod/ghk.inc
	graham$ git push
	Counting objects: 4, done.
	Delta compression using up to 8 threads.
	Compressing objects: 100% (4/4), done.
	Writing objects: 100% (4/4), 742 bytes | 742.00 KiB/s, done.
	Total 4 (delta 2), reused 0 (delta 0)
	remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
	To https://github.com/Neurosim-lab/EEE_network.git
	   700cd24..5fb1177  master -> master

So everything should work now.  Trying it out.

	graham$ cd ~
	graham$ rm -rf EEE_network/
	graham$ git clone https://github.com/Neurosim-lab/EEE_network.git
	graham$ cd EEE_network/mod/
	graham$ nrnivmodl

Works perfectly now.  

Need to symlink mod/x86_64 into eee_network

	graham$ ln -s /Users/graham/EEE_network/mod/x86_64 /Users/graham/EEE_network/eee_network/x86_64

Now hopefully everything works.

*** Running EEE network sim

To debug in Netpyne, run files in the following order:

1) netParams.py 
2) batch_init.py (just init.py in this case) 
3) batch.py

Trying to run netParams.py:
	graham$ python netParams.py 
	Traceback (most recent call last):
	  File "netParams.py", line 1, in <module>
	    from netpyne import specs
	ModuleNotFoundError: No module named 'netpyne'

Need to install Netpyne (development version to immediately get fixes):
http://www.netpyne.org/install.html#install-via-pip-development-version

	1. git clone https://github.com/Neurosim-lab/netpyne.git
	2. cd netpyne
	3. git checkout development
	4. pip install -e .

	pip will add a symlink in the default python packages folder to the cloned netpyne folder (so you don’t need to modify PYTHONPATH). If new changes are available just need to pull from cloned netpyne repo.

Commands:
	graham$ cd ~/Applications/
	graham$ git clone https://github.com/Neurosim-lab/netpyne.git
	graham$ cd netpyne/
	graham$ git checkout development
	graham$ pip install -e .

Everything seems to have worked.

Trying to run netParams again:
	
	graham$ cd ~/EEE_network/eee_network/
	graham$ python netParams.py
	Note: NeuroML import failed; import/export functions for NeuroML will not be available. 
	  To install the pyNeuroML & libNeuroML Python packages visit: https://www.neuroml.org/getneuroml
	Traceback (most recent call last):
	  File "netParams.py", line 95, in <module>
	    for secName,sec in netParams.cellParams['PT5_1']['secs'].iteritems():         
	TypeError: 'Dict' object is not callable

Seems to be a problem with Python 2 --> 3
https://github.com/mgymrek/itable/issues/9
https://stackoverflow.com/questions/10458437/what-is-the-difference-between-dict-items-and-dict-iteritems

I changed two `iteritems` in netParams to `items` and now it works.

So netParams works now.  Now to run init.py

	graham$ python init.py

Something's not quite right:

	Plotting raster...
	There was an exception in plotRaster(): 
	 "['tags'] not found in axis" 
	(<class 'KeyError'>, KeyError("['tags'] not found in axis"), <traceback object at 0x12223ea88>)

Also, traces plot appeared in eee_network dir, but it's blank.

Also, there are too few cells...

Line 130 in cfg.py was:
cfg.singleCellPops = True

Changed it to False and trying again.

Running netParams works fine.  
When I run init, it seems like there are no connections and no traces recorded:

	Creating network of 5 cell populations on 1 hosts...
	  Number of cells on node 0: 1500 
	  Done; cell creation time = 4.66 s.
	Making connections...
	  Number of connections on node 0: 0 
	  Done; cell connection time = 0.00 s.
	  Number of stims on node 0: 0 
	  Done; cell stims creation time = 0.00 s.
	Recording 0 traces of 0 types on node 0

Still getting raster error and blank traces plot.


Changing from hpc_slurm to mpi in batch.py:
#setRunCfg(b, type='hpc_slurm')
setRunCfg(b, type='mpi')

Trying to run batch.py

Getting an error:
	graham$ python batch.py
	Traceback (most recent call last):
	  File "batch.py", line 8, in <module>
	    from netpyne.batch import Batch, specs
	ImportError: cannot import name 'specs' from 'netpyne.batch' (/Users/graham/Applications/netpyne/netpyne/batch/__init__.py)

It seems like I should change importing specs from netpyne.batch to just from netpyne...

Changing batch.py and trying again.

Getting a new error:
	FileNotFoundError: [Errno 2] No such file or directory: 'batch_data/stim_batch6/stim_batch6_batch.json'

I think the dir must already exist...  Changing batch.py to remove need for
extra dir.

New error:
	Error: invalid runCfg 'type' selected; valid types are 'mpi_bulletin', 'mpi_direct', 'hpc_slurm', 'hpc_torque'

Will have to look into this.  Asked Salva:

	joe [9:59 AM]
	Hey Salva, it seems Netpyne used to accept `mpi` as a runCfg option, but now Netpyne requires `mpi_direct` or `mpi_bulletin`…

	Untitled 
	Error: invalid runCfg 'type' selected; valid types are 'mpi_bulletin', 'mpi_direct', 'hpc_slurm', 'hpc_torque'
	Would you mind explaining the difference between `direct` and `bulletin`?
	i.e. which should I be using?

	salvadord [10:03 AM]
	mpi_bulletin - uses NEURON’s mpi bulletin board (master slave) to run the batch sim — there is a master node that sends jobs (each sim) to the slave nodes

	joe [10:05 AM]
	And what does `mpi_direct` do?

	salvadord [10:07 AM]
	mpi_direct - runs each of the batch jobs directly using mpi by calling mpirun via Popen (a pipe) — can specify the number of cores of each mpi job … eg say you have a machine with 16 cores, you could run 4 of the batch jobs on 4 cores each simultaneously
	with mpi_bulleting, each job is always on a single core
	*mpi_bulletin

Okay, so switching to `mpi_bulletin` (seems less complicated):
Changing all `mpi` in batch.py to `mpi_bulletin`

Now batch.py seems to run, but Sergio's default batch was huge: four 
variables each with multiple values.  Will need to set up a smaller batch.  

For now, will look into why there are no connections and no traces.

Running single sim:

graham$ cd ~/EEE_network/eee_network/
graham$ ./runsim

It runs, but no connections or output traces.  Looking into it...

The lack of connectivity is because the connectivity stuff has been commented out. Once we have it working and are getting output we can worry about connectivity.

Having a hard time figuring out the problem with lack of output figures.
I tried adding a soma recording to the cfg file, and when I look in the output json file, the soma trace data is there, but the trace plot output is blank...

Reducing sim time to 50 ms to speed things up.  Commenting out basal trace recording in cfg.

Same thing.  No output traces.

The code is really convoluted.  I'm beginning to think it would be better to start from our cell models and build up network sims from scratch...

Will push my stuff to the git repo now.  Creating a new branch: joes_branch

Cloning, switching to joes_branch, swapping in my changes, then pushing.


* 2019-01-11 -- EEE Network Meeting

In progress
-----------
Summarize current network model
Prepare for discussion with EEE team
Meeting 12pm Eastern to discuss network

** Steps to run network sim

cd ~
git clone https://github.com/Neurosim-lab/EEE_network.git
cd EEE_network/
git checkout joes_branch
cd mod
nrnivmodl
ln -s ~/EEE_network/mod/x86_64 ~/EEE_network/x86_64
cd ../eee_network
./runsim

** EEE Network Sim Meeting -- 2018-01-11
https://docs.google.com/document/d/1jKOPmc2PkjyJme_dgMKip7mLxlXXPuehVY4q-qeBWZs/edit

Google Hangout URL: https://hangouts.google.com/call/UFV-belsSHz1VJv5J4ozAAEE 

Today’s agenda

How to start developing the network model
List of tasks
Division of tasks
	
Discussion

Current state
Disorganized

Network sim development plan
  Scrap existing model
  Two populations: Netpyne tutorial 5
  How many populations? Two
  Where data?  Connectivity?
    Layer 5 IT cells connectivity
    PV cells from M1 model
  Background inputs
  Inputs to both pops
  Want baseline oscillations
How to divide E cells
  Sergio had multiple -- good way to start
  Can force plateaus on subset
How to distribute synapses on neurons
  Bill: 500 inputs 
  One basal has convergence
  Look into clustering
  Strong convergence onto dend A then B
  Other dend possible synchronicity source
Number of cells: ~5000
Trello for task management
Goal of network
  Use existing cell models
  Plug into network
  Look for ensembles
  Preferably emergent
  Synchrony in embedded ensembles
  Activated → Synced
Tasks to be accomplished
  Joe gets framework in place
  Then we divvy up tasks


* 2019-01-15 -- Setting up new network model, EEE Meeting

In progress
-----------
Netpyne Tutorial 5 as basis for network model
Get new model framework into Github
List of synaptic clustering articles
Meeting 11am Eastern - prepare agenda

** Netpyne Tutorial 5

http://netpyne.org/tutorial.html#position-and-distance-based-connectivity-tutorial-5

Downloaded tut5.py and it runs, though I needed to uncomment the following line to see figures:

	import pylab; pylab.show()  # this line is only necessary in certain systems where figures appear empty

The figures should have been saved as well, but never appeared.  Will look into this later.

Downloaded runsim in order to parallelize sims:
	
	#!/bin/bash
	mpiexec -n $1 nrniv -python -mpi $2  # Run the model

Changed permissions on runsim so I can execute:

	graham$ chmod +x runsim

Now splitting tut5.py into three files: 
	
	netParams.py
	cfg.py
	init.py

Changing runsim to call init.py:

	#!/bin/bash
	# Runs simulation, including MPI.

	numprocesses=$1; if [ -z $numprocesses ]; then numprocesses=4; fi # Number of processes to use
	shift # Eliminate first argument

	mpiexec -np $numprocesses nrniv -python -mpi init.py $@  # Run the model

Copying init.py from earlier network sim:

	"""
	init.py

	Usage:
	    python init.py # Run simulation, optionally plot a raster

	MPI usage:
	    mpiexec -n 4 nrniv -python -mpi init.py

	Contributors: salvadordura@gmail.com
	"""

	#import matplotlib; matplotlib.use('Agg')  # to avoid graphics error in servers
	from netpyne import sim

	simConfig, netParams = sim.readCmdLineArgs()
	#sim.createSimulateAnalyze()

	sim.initialize(
	    simConfig = simConfig,    
	    netParams = netParams)        # create network object and set cfg and net params
	sim.net.createPops()              # instantiate network populations
	sim.net.createCells()             # instantiate network cells based on defined populations
	sim.net.connectCells()            # create connections between cells based on params
	sim.net.addStims()                # add network stimulation
	sim.setupRecording()              # setup variables to record for each cell (spikes, V traces, etc)
	sim.runSim()                      # run parallel Neuron simulation  
	sim.gatherData()                  # gather spiking data and cell info from each node
	sim.saveData()                    # save params, cell info and sim output to file (pickle,mat,txt,etc)
	sim.analysis.plotData()           # plot spike raster etc


Now to break tut5.py into netParams and cfg and try to run.

	graham$ ./runsim 1
	numprocs=1
	NEURON -- VERSION 7.6.4 master (50728e66) 2018-12-14
	Duke, Yale, and the BlueBrain Project -- Copyright 1984-2018
	See http://neuron.yale.edu/neuron/credits

	Note: NeuroML import failed; import/export functions for NeuroML will not be available. 
	  To install the pyNeuroML & libNeuroML Python packages visit: https://www.neuroml.org/getneuroml

	Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

	Warning: Could not load cfg from command line path or from default cfg.py

	Creating network of 6 cell populations on 1 hosts...
	  Number of cells on node 0: 300 
	  Done; cell creation time = 0.03 s.
	Making connections...
	  Number of connections on node 0: 6796 
	  Done; cell connection time = 0.67 s.
	Adding stims...
	  Number of stims on node 0: 300 
	  Done; cell stims creation time = 0.03 s.

	Running simulation for 1000.0 ms...
	  Done; run time = 3.08 s; real-time ratio: 0.32.

	Gathering data...
	  Done; gather time = 0.17 s.

	Analyzing...
	  Cells: 300
	  Connections: 7096 (23.65 per cell)
	  Spikes: 4879 (16.26 Hz)
	  Simulated time: 1.0 s; 1 workers
	  Run time: 3.08 s
	  Done; saving time = 0.01 s.
	  Done; plotting time = 0.00 s

	Total time = 4.00 s
	>>> 

No figures, and it doesn't seem to have worked:

	Warning: Could not load cfg from command line path or from default cfg.py

It seems the problem may be that in tut5.py we named the config object simConfig instead of cfg...

	simConfig = specs.SimConfig()

Will change all config file lines to:
	
	cfg = specs.SimConfig()

Commenting out line that runs sim in cfg.py

Renaming simConfig to cfg in init.py

Trying to run sim.

	graham$ ./runsim 1

Sim ran successfully, figures appeared but weren't saved.  Off to a good start.

Now that the sim is functional, I'll push to Github.

How I was taught to develop code:
	
	Step 1: make it run.
	Step 2: make it right.
	Step 3: make it fast.

Now to work on Step 2 while ensuring Step 1 continues to work.

Next steps:

Use our cell models
Modify population parameters 

** Updating the README

	# EEE_network

	## Steps to run the network simulation:

	1. cd ~
	2. git clone https://github.com/Neurosim-lab/EEE_network.git
	3. cd EEE_network/
	4. git checkout joes_branch
	5. cd mod
	6. nrnivmodl
	7. cd ../eee_net
	8. ln -s "../mod/x86_64" x86_64
	9. ./runsim

Tested these steps and they work from any location (not just home).

** Meeting agenda / notes

https://docs.google.com/document/d/1kZGWeilbLhc9Lv9ly82xLqsqFRsdW6iAsQdeytzcUXo/edit

*** Upcoming deadlines:

IMAG:		Feb 1, 11:59 EST
https://msmmeeting.nibib.nih.gov/instructions-for-submitting-materials

CNS: 		March 4, 11pm Pacific time
https://www.cnsorg.org/cns-2019-abstract-submission

BRAIN:	March 11, 5pm EST
http://www.cvent.com/events/5th-annual-brain-initiative-investigators-meeting/custom-117-de9c0d8f934b46eb8d80b55bcfbfe96a.aspx

SfN: 		May 2, 5pm EDT
https://www.sfn.org/Meetings/Neuroscience-2019/Dates-and-Deadlines

*** Network Meeting summary

2 populations (E and I)
E from Penny’s single cell model (simplified)
I from PV cells in Salva’s M1 model
5000 cells, 500 inputs per cell
Background inputs to both pops → oscillations
First force plateaus and explore sims
Work towards emergent plateaus / ensembles

Framework for network sims is in joes_branch in EEE_network/eee_net
https://github.com/Neurosim-lab/EEE_network/tree/joes_branch/eee_net

Currently it’s just Netpyne Tutorial 5 broken down into the files needed for organizing a larger simulation, but it runs
Next steps: swapping in our cell models, modifying pop parameters, etc.


** Synaptic clustering articles

Need to read these and pull relevant info.

Synaptic clustering articles:

Single excitatory axons form clustered synapses onto CA1 pyramidal cell dendrites
https://www.nature.com/articles/s41593-018-0084-6
“Here we show that single presynaptic axons form multiple, spatially clustered inputs onto the distal, but not proximal, dendrites of CA1 pyramidal neurons.”

Synaptic clustering by dendritic signalling mechanisms
https://www.sciencedirect.com/science/article/abs/pii/S095943880800086X
“Dendrites are endowed with mechanisms of nonlinear summation of synaptic inputs leading to regenerative dendritic events including local sodium, NMDA and calcium spikes. The generation of these events requires distinct spatio-temporal activation patterns of synaptic inputs. We hypothesise that the recent findings on dendritic spikes and local synaptic plasticity rules suggest clustering of common inputs along a subregion of a dendritic branch.”

Synaptic clustering within dendrites: An emerging theory of memory formation
https://www.sciencedirect.com/science/article/pii/S0301008214001373
“The emerging picture suggests that clusters of functionally related synapses may serve as key computational and memory storage units in the brain. We discuss both experimental evidence and theoretical models that support this hypothesis and explore its advantages for neuronal function.”

Synaptic clustering during development and learning: the why, when, and how
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3364493/
“Previous modeling and experimental studies have predicted that this specificity could entail a subcellular organization whereby synapses that carry similar information are clustered together on local stretches of dendrite. Recent imaging studies have now, for the first time, demonstrated synaptic clustering during development and learning in different neuronal circuits.”

Clusters of synaptic inputs on dendrites of layer 5 pyramidal cells in mouse visual cortex
https://elifesciences.org/articles/09222
“We mapped the spatial organization of glutamatergic synapses between layer 5 pyramidal cells by combining optogenetics and 2-photon calcium imaging in mouse neocortical slices. To mathematically characterize the organization of inputs we developed an approach based on combinatorial analysis of the likelihoods of specific synapse arrangements. We found that the synapses of intralaminar inputs form clusters on the basal dendrites of layer 5 pyramidal cells. These clusters contain 4 to 14 synapses within ≤30 µm of dendrite.”


* 2019-01-17 -- Setting up EEE populations

In progress
-----------
Setting up network model
Get our cell models in
Adjust population parameters
Set initial connectivity to Sergio's settings?

** Adjusting population properties

Sergio's original code:

	# add excitatory populations
	excPopLabels = ['PT5_1', 'PT5_2', 'PT5_3', 'PT5_4'] 
	for k,label in enumerate(excPopLabels):
	    netParams.popParams[label]  = {'cellModel': 'HH_reduced', 'cellType': label,  'xRange': columnA, 'ynormRange': layer['5'], 'numCells': numcellsPT5} 

	# add inhibitory population
	netParams.popParams['PV5']  = {'cellModel': 'HH_simple',  'cellType': 'PV','xRange': columnA, 'ynormRange': layer['5'], 'numCells': numcellsPV5} 

The layer['5'] comes from:
	
	# layer boundaries
	layer = {'5': [0.2,0.623], 'long': [0.7,1.0]} # yRange in column

Code from tutorial:

	netParams.popParams['E2'] = {'cellType': 'E', 'numCells': 50, 'yRange': [100,300], 'cellModel': 'HH'}
	netParams.popParams['I2'] = {'cellType': 'I', 'numCells': 50, 'yRange': [100,300], 'cellModel': 'HH'}
	netParams.popParams['E4'] = {'cellType': 'E', 'numCells': 50, 'yRange': [300,600], 'cellModel': 'HH'}
	netParams.popParams['I4'] = {'cellType': 'I', 'numCells': 50, 'yRange': [300,600], 'cellModel': 'HH'}
	netParams.popParams['E5'] = {'cellType': 'E', 'numCells': 50, 'ynormRange': [0.6,1.0], 'cellModel': 'HH'}
	netParams.popParams['I5'] = {'cellType': 'I', 'numCells': 50, 'ynormRange': [0.6,1.0], 'cellModel': 'HH'}

New code:

	## Population parameters
	netParams.popParams['PT5_1'] = {'cellType': 'E', 'numCells': 200, 'ynormRange': [0.2,0.623], 'cellModel': 'HH'}
	netParams.popParams['PT5_2'] = {'cellType': 'E', 'numCells': 200, 'ynormRange': [0.2,0.623], 'cellModel': 'HH'}
	netParams.popParams['PT5_3'] = {'cellType': 'E', 'numCells': 200, 'ynormRange': [0.2,0.623], 'cellModel': 'HH'}
	netParams.popParams['PT5_4'] = {'cellType': 'E', 'numCells': 200, 'ynormRange': [0.2,0.623], 'cellModel': 'HH'}
	netParams.popParams['PV5'] = {'cellType': 'I', 'numCells': 200, 'ynormRange': [0.2,0.623], 'cellModel': 'HH'}

Getting a strange NEURON error. Looking through netParams for any other necessary changes.

The I-->E pops need to be changed, from:

	netParams.connParams['I->E'] = {
	  'preConds': {'cellType': 'I'}, 'postConds': {'pop': ['E2','E4','E5']},       #  I -> E
	  
To:

	netParams.connParams['I->E'] = {
	  'preConds': {'cellType': 'I'}, 'postConds': {'pop': ['E']},       #  I -> E

Trying again.

Hmmm.  When I run it using once core, it seems to complete the sim, but stalls at the connectivity plot.  (There are 79621 connections, which probably would take awhile to plot...)

Reducing the number of cells and trying again.

Now it works and plots.  Trying it with multiple cores.

Still works.  Will add a variable to set the number of neurons.

Still works.  I have succesfully renamed the populations.

Now to use our cell models.  But first committing.


* 2019-01-18 -- Plugging PV5 model into network

In progress
-----------
Setting up network model
Get our cell models in
Set initial connectivity to Sergio's settings?

** Get our cell models in

Using info from here:
http://netpyne.org/advanced.html#importing-cells

*** Trying to swap in the PV5 cell model first

Sergio's code (from netParams.py):

	# Find path to cells directory
	cellpath = '../cells'
	eeeS_path = os.path.join(cellpath, 'eeeS.py')
	PV_path   = os.path.join(cellpath, 'FS3.hoc')

	# Import and modify PT5 cell
	cellRule = netParams.importCellParams(label='PT5_1', conds={'cellType': 'PT5_1', 'cellModel': 'HH_reduced'}, fileName=eeeS_path, cellName='MakeCell')

	# Import PV5 cell
	cellRule = netParams.importCellParams(label='PV5', conds={'cellType':'PV', 'cellModel':'HH_simple'}, fileName=PV_path, cellName='FScell1', cellInstance = True)

First changing all cellTypes from tutorial's E and I to PT5 and PV

Starting with importing the PV5 cell.

	## Import PV5 cell
	cellRule = netParams.importCellParams(label='PV5', conds={'cellType':'PV'}, fileName=PV_path, cellName='FScell1', cellInstance=True)
	netParams.cellParams['PVrule'] = cellRule

And attempting to run sim.

Getting an error:

	graham-mac:eee_net graham$ ipython -i netParams.py
	Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
	Type 'copyright', 'credits' or 'license' for more information
	IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.
	NEURON: syntax error
	 in FS3.hoc near line 37
	      insert Nafx
	                ^
	        xopen("FS3.hoc")
	      execute1("{xopen("FS...")
	    load_file("../cells/F...")
	Segmentation fault: 11

Looking into it.

I think I need to symlink the x86_64 dir into the dir eee_net...

That worked.  Now ./runsim works and generates figures, but PT5 trace figures didn't show up (PV5 trace figure did).  Looking into.

I changed the cellType of all PT5 pops from PT5_# to just PT5.  Switching back and seeing if trace figures work again.

Still none.

Ahh, I had commented out the code setting up the PT cells because I wasn't ready.  Uncommenting and checking.

Changed E to PT5:

	## Cell property rules
	cellRule = {'conds': {'cellType': 'PT5'},  'secs': {}}  # cell rule dict
	cellRule['secs']['soma'] = {'geom': {}, 'mechs': {}}                              # soma params dict
	cellRule['secs']['soma']['geom'] = {'diam': 15, 'L': 14, 'Ra': 120.0}                   # soma geometry
	cellRule['secs']['soma']['mechs']['hh'] = {'gnabar': 0.13, 'gkbar': 0.036, 'gl': 0.003, 'el': -70}      # soma hh mechanism
	netParams.cellParams['Erule'] = cellRule  

Now everything works fine.  Will commit and then insert eeeS cell model.


* 2019-01-21 -- Importing eeeS, gitting back to master

In progress
-----------
Setting up network model
Get our cell models in
Set initial connectivity to Sergio's settings?

** Chats 

	don [9:18 AM]
	joe, how is the code coming along. please let me know if there is anything i may help with

	joe [9:30 AM]
	I’m just sitting down at it now.  Right now it’s just Netpyne tutorial 5 broken into separate files.  I’m about to start setting it up how we discussed in the meeting.
	But if you could try running it now, that’d be great, and then you can help plug in the cell models, set the parameters, etc. with me.
	It’s in my branch right now: https://github.com/Neurosim-lab/EEE_network/tree/joes_branch
	GitHub
	Neurosim-lab/EEE_network
	Contribute to Neurosim-lab/EEE_network development by creating an account on GitHub.
	The README should explain how to run it.

	don [9:37 AM]
	ok … doing now

	don [9:45 AM]
	looks like i just pulled the same as before
	your branch is selected and then i clone
	i ran init.py

	joe [9:46 AM]
	After you clone, you have to `git checkout joes_branch`

	don [9:46 AM]
	oh, sorry!

	joe [9:47 AM]
	No worries.  git is confusing.

	joe [10:00 AM]
	So I left the old stuff in eee_network (so we can mine it for useful code) and I am now developing eee_net

	don [10:00 AM]
	ran. seems to run fine. gui windows appeared but i didn
	’t wait for content to appear
	need to run but will be back at it in about 1 hour

	joe [10:01 AM]
	:+1:

	don [12:48 PM]
	sorry, was pulled away longer than expected
	did a git fetch when i returned … guess you hadn’t updated repo?

	don [12:54 PM]
	running and displaying fine
	don’t want to redo that which you’ve already done so please assign me a task and i will do

	joe [2:25 PM]
	I’m trying to get all the old parameters and settings into the new model.  Probably won’t be done until sometime tomorrow.  Might as well wait until then to get you going so we don’t overlap.

	don [3:07 PM]
	Ok

	don [8:56 AM]
	how’s it going joe?

	joe [9:18 AM]
	Slowly, but it’s going.  I got the EEE populations into the model yesterday.  This morning I’m working on getting our cell models in.
	If you wanted to update your repo and make sure it still runs on your machine, that would be helpful.

	don [9:30 AM]
	already did and does ;)

	joe [9:33 AM]
	Sweet, thanks.  I’ll let you know when I get the cells in.

	don [9:48 AM]
	are the cells the ones in EEE_singlecell_simplified?

	joe [9:52 AM]
	We’ve got them in the repo as: `EEE_network/cells/eeeS.py` and `EEE_network/cells/FS3.hoc`
	But actually, there is something you could do that wouldn’t overlap!
	I’ve been meaning to re-compare `eeeS.py` with Penny’s detailed model again (it’s been awhile and she probably made some changes).
	We want to use all the same mod files, all the same parameter values, etc.

	joe [11:45 AM]
	Got the PV model cell inserted and working.  After lunch I’ll get the eeeS model plugged in.

	don [6:28 AM]
	Where can I find Penny’s original detailed model? Maybe EEE_singlecell_simplified? But says “simplified” not detailed model.

	joe [3:08 PM]
	Hmmm.  I’ll have to look for it.

	joe [3:12 PM]
	Hey Penny, Don is going to make sure that our simplified model uses all the same mod files and parameter values as your detailed model.  Is there some way we can access your current detailed model?

	penny [5:47 PM]
	Hello, here it is: https://github.com/super-penguin/EEE_Detailed_Cell. We are using the same mod files :-)
	GitHub
	super-penguin/EEE_Detailed_Cell
	A detailed model of prefrontal L5 pyramidal neuron --- for EEE project - super-penguin/EEE_Detailed_Cell
	But some of the parameters are a little bit different. I made changes to the simplified model from the network github repo before, but didn’t push it. I will push it tonight

	don [6:15 PM]
	great! thank you penny

	penny [7:27 PM]
	:+1:

	joe [7:47 PM]
	Thanks Penny!

	penny [12:39 AM]
	Hmmm, if I add a pull request, the new changes will be merged into the neurosim-lab/EEE_network master branch without permission. Is this how its set up?
	I just add a pull request, let me know if something is not right. Hope I didn’t mess up the repo

	joe [11:10 AM]
	Thanks, Penny! I don’t have a lot of experience with Git, but it looks like your pull request is great.  I’m just about to try inserting eeeS into the network model.  Once I get that working I’ll figure out how to merge my changes into the master branch.  :sweat_smile:

	penny [11:11 AM]
	Great! Thanks. I am pretty new to group work on github too:joy:


** Updating eeeS

I accepted Penny's pull request in the master branch, so the updated eeeS model is there.

I'm working in joes_branch though, so I need to get the latest model into my branch also.

I think I'll just download it from the master branch and copy and paste it into my local repo of joes_branch.

Cloning repo into temp, copying eeeS.py over to my repo of joes_branch.

That worked.  

	graham-mac:EEE_network graham$ git status
	On branch joes_branch
	Your branch is up to date with 'origin/joes_branch'.

	Changes not staged for commit:
	  (use "git add <file>..." to update what will be committed)
	  (use "git checkout -- <file>..." to discard changes in working directory)

		modified:   cells/eeeS.py
		modified:   nb_graham.org


Committing now.

** Swapping eeeS into network model

Here's how we now import the PV5 cell model:

	## Import PV5 cell
	cellRule = netParams.importCellParams(label='PV5', conds={'cellType':'PV'}, fileName=PV_path, cellName='FScell1', cellInstance=True)
	netParams.cellParams['PVrule'] = cellRule

Here's how we used to import the eeeS model:

	# Import and modify PT5 cell
	cellRule = netParams.importCellParams(label='PT5_1', conds={'cellType': 'PT5_1', 'cellModel': 'HH_reduced'}, fileName=eeeS_path, cellName='MakeCell')

But then to get separate pops, we used to copy the first cell rule:

	# make copy of cell rule for the other 3 pops
	# note: we are creating 1 cell type per pop because they could potentially have different Gfluct params           
	for k,label in enumerate(excPopLabels[1:]):    
	        cellRule = copy.deepcopy(netParams.cellParams['PT5_1'].todict())
	        cellRule['conds']['cellType'] = [label]
	        netParams.cellParams[label] = cellRule

Where

	excPopLabels = ['PT5_1', 'PT5_2', 'PT5_3', 'PT5_4']

I'm not quite sure what `cellInstance=True` does...  Can't find it anywhere in the Netpyne documentation.  I'll ask Salva.


** Asking Salva for help

	joe [11:43 AM]
	Hey Salva, in our old network code, when we did a `cellRule = netParams.importCellParams` we included the option `cellInstance=True`, but that never appears in the tutorial code, and I can’t find it in the Netpyne documentation.  Do you know if that does anything?

	salvadord [11:45 AM]
	yes it does … unfotunately a lot of stuff not documented
	cellInstance = True means you are extracting the cell parameters from a cell that has been instantiated from a template (hoc template or python class) instead of fromthe template itself (which is the default
	i.e. in the file you are importing from there’ll be something like `cell = PTCell()`

	joe [11:48 AM]
	Pretty sure I understand the distinction, just not sure what difference it would make.  I.e., is there a reason we need it for our eee network sims?

	joe [12:01 PM]
	One more question: in the old code, we used `importCellParams` once for PT5_1, and then deepcopied the cellRule three times for PT5_2, etc.  To me, this is less intuitive than just running `importCellParams` four times…  Does the copying offer some advantage I don’t see?

	salvadord [12:03 PM]
	no difference after being imported — just needed for some cases where eg. need to instantiate cell first because need to call cell class methdos that set some cell params
	needed for eee — not sure, I can check
	copying advantage - faster, since importing internally requires actually creating the cell in Neuron and using a bunch of Neuron funcs to extract all the params
	ideally all the cell params would remain the same, so could just create multiple populations from the same cellParams rule — however due to the setup of the artif noise input to cell, I think needed different cellParams entries

	joe [12:06 PM]
	Great, thanks Salva!

** Inserting eeeS cell model

New code:

	## Import eeeS cell (PT5)
	cellRule = netParams.importCellParams(label='PT5_1', conds={'cellType':'PT5_1'}, fileName=eeeS_path, cellName='MakeCell', cellInstance=True)
	netParams.cellParams['PT5_1'] = cellRule

	## Then copy the cellRule for the other pops (faster than importing again)
	## Note: we are creating 1 cell type per pop because they could potentially have different noise and connectivity params           
	for label in ['PT5_2', 'PT5_3', 'PT5_4']:    
	    cellRule = copy.deepcopy(netParams.cellParams['PT5_1'].todict())
	    cellRule['conds']['cellType'] = [label]
	    netParams.cellParams[label] = cellRule

And trying it out.  It ran, but not all figures appeared.  Need to change recording options to match cellTypes.

Actually, it already matched cellTypes.  The problem is that our eeeS cells have more than one soma compartment, requiring the following to record somas from both PV5 cells and PT5 (eeeS):

	cfg.recordTraces = {'V_soma':{'sec':'soma','loc':0.5,'var':'v'}}  # Dict with traces to record
	cfg.recordTraces['V_soma_0'] = {'sec':'soma_0','loc':0.5,'var':'v'}

The first line gets the soma from the PV cells, the second line gets a soma from the PT cells.  Problem is, neither has the other soma section, so trace-plotting gets hinky.

Easiest thing to do right now is probably compress the soma of eeeS into one compartment.  This will require figuring out how to keep the same surface area / volume, reconnecting all other branches to single soma, and testing before and after change to ensure they're the same.

About to go to lunch, so I'll see if Penny and Don can handle this.

** Chat with Penny and Don

	joe [12:41 PM]
	Hey Penny and Don, I’m still working on getting the network up and running, but there is something you guys could do in the meantime, if you have time.
	I’m having problems with figures.  PV cells have single soma compartment while eeeS cells have several.  That means I have to record two traces to see soma (`soma` in PV and `soma_0` or `soma_1` etc. in eeeS).  Since the other cell type doesn’t have that section, the figures break.
	I think the easiest fix would be just to collapse the several soma compartments in eeeS into a single one.
	This would require reconnecting branches to the new single soma and matching surface area/volume between multiple and new single cylinder.
	Then we’d probably want to run inputs into old multi-soma and new single-soma to ensure they behave the same.
	I’m about to head to lunch, but I’ll be back later.

	don [1:41 PM]
	i’m looking though newly fetched EEE_network … not seeing new stuff. maybe i’m looking in wrong place?

	joe [2:04 PM]
	I’m working in `joes_branch` in the `eee_net` directory.  The `eee_network` directory is the old stuff I’m keeping around until we get all useful code out of it.

	don [2:05 PM]
	makes sense

	penny [2:11 PM]
	Got it. Will look into it soon :slightly_smiling_face:


** Using cellType different from pop name

Was having to do a lot of work to connect pops.  Instead of having each pop having a cellType set to its name, all PT5 pops now have cellType PT5.

Now I can wire individually to a pop or collectively to a cellType.

e.g. conds: {'pop': PT5_1} or conds: {'cellType': PT5}

And running.  Looks good except background seems to have zero connectivity.

Problem was I was using old cellTypes in the bkg setting.

Changed from this:

	netParams.stimTargetParams['bkg->all'] = {'source': 'bkg', 'conds': {'cellType': ['PV','PT5_1','PT5_2','PT5_3','PT5_4']}, 'weight': 0.01, 'delay': 'max(1, normal(5,2))', 'synMech': 'exc'}

To this:

	netParams.stimTargetParams['bkg->all'] = {'source': 'bkg', 'conds': {'cellType': ['PV5','PT5']}, 'weight': 0.01, 'delay': 'max(1, normal(5,2))', 'synMech': 'exc'}

Now it works and everything looks good.

Committing.

** Replacing master branch with joes_branch

Now that my branch is working, I want to actually replace everything in the master branch with my own.

https://stackoverflow.com/questions/2862590/how-to-replace-master-branch-in-git-entirely-from-another-branch

Cleaned up some extraneous comments.  Committing now and then will attempt the branch grafting.

Commands to graft:

	git checkout joes_branch
	git merge -s ours master
	git checkout master
	git merge joes_branch

Doesn't seem to be working.  

	graham$ git merge -s ours master
	Already up to date.

I'm going to do it quick and dirty.  First, I'll make a branch copy of master named old_master.  

	graham-mac:EEE_network graham$ git checkout master
	Switched to branch 'master'
	Your branch is up to date with 'origin/master'.
	graham-mac:EEE_network graham$ git branch -m master old_master
	graham-mac:EEE_network graham$ git branch
	  joes_branch
	* old_master
	graham-mac:EEE_network graham$ git push
	fatal: The upstream branch of your current branch does not match
	the name of your current branch.  To push to the upstream branch
	on the remote, use

	    git push origin HEAD:master

	To push to the branch of the same name on the remote, use

	    git push origin old_master

	graham-mac:EEE_network graham$ git push origin old_master
	Total 0 (delta 0), reused 0 (delta 0)
	remote: 
	remote: Create a pull request for 'old_master' on GitHub by visiting:
	remote:      https://github.com/Neurosim-lab/EEE_network/pull/new/old_master
	remote: 
	To https://github.com/Neurosim-lab/EEE_network.git
	 * [new branch]      old_master -> old_master
	graham-mac:EEE_network graham$ 


Now to forcefully replace master with joes_branch

	graham-mac:EEE_network graham$ git checkout master
	error: Your local changes to the following files would be overwritten by checkout:
		nb_graham.org
	Please commit your changes or stash them before you switch branches.
	Aborting
	graham-mac:EEE_network graham$ 

Oops.  Need to commit the notebook changes first.

	graham-mac:EEE_network graham$ git checkout master
	error: Your local changes to the following files would be overwritten by checkout:
		nb_graham.org
	Please commit your changes or stash them before you switch branches.
	Aborting
	graham-mac:EEE_network graham$ git status
	On branch joes_branch
	Your branch is up to date with 'origin/joes_branch'.

	Changes not staged for commit:
	  (use "git add <file>..." to update what will be committed)
	  (use "git checkout -- <file>..." to discard changes in working directory)

		modified:   nb_graham.org

	Untracked files:
	  (use "git add <file>..." to include in what will be committed)

		cells/__pycache__/
		eee_net/__pycache__/
		eee_net/x86_64
		eee_network/__pycache__/
		mod/x86_64/
		x86_64

	no changes added to commit (use "git add" and/or "git commit -a")
	graham-mac:EEE_network graham$ git add nb_graham.org 
	graham-mac:EEE_network graham$ git status
	On branch joes_branch
	Your branch is up to date with 'origin/joes_branch'.

	Changes to be committed:
	  (use "git reset HEAD <file>..." to unstage)

		modified:   nb_graham.org

	Untracked files:
	  (use "git add <file>..." to include in what will be committed)

		cells/__pycache__/
		eee_net/__pycache__/
		eee_net/x86_64
		eee_network/__pycache__/
		mod/x86_64/
		x86_64

	graham-mac:EEE_network graham$ git commit -m "Notebook commit before branch grafting."
	[joes_branch 6251998] Notebook commit before branch grafting.
	 1 file changed, 52 insertions(+)
	graham-mac:EEE_network graham$ git checkout master
	Switched to branch 'master'
	Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
	  (use "git pull" to update your local branch)
	graham-mac:EEE_network graham$ git pull
	Updating 5fb1177..1f6a291
	Fast-forward
	 cells/eeeS.py | 64 +++++++++++++++++++---------------------------------------------
	 1 file changed, 19 insertions(+), 45 deletions(-)
	graham-mac:EEE_network graham$ git reset --hard joes_branch
	HEAD is now at 6251998 Notebook commit before branch grafting.
	graham-mac:EEE_network graham$ git push -f origin master
	Counting objects: 3, done.
	Delta compression using up to 8 threads.
	Compressing objects: 100% (3/3), done.
	Writing objects: 100% (3/3), 953 bytes | 953.00 KiB/s, done.
	Total 3 (delta 2), reused 0 (delta 0)
	remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
	To https://github.com/Neurosim-lab/EEE_network.git
	 + 1f6a291...6251998 master -> master (forced update)
	graham-mac:EEE_network graham$ 

That seems to have worked fine.  :)

Updating the README.

Committing then pushing.


* 2019-01-22 -- EEE Meeting and various fixes

In progress
-----------
Setting up network model
Set up synaptic mechanisms
Set initial connectivity to Sergio's settings

** EEE meeting

Agenda:
https://docs.google.com/document/d/1ifVpuQo0gJJhj8epg4cWRoeJSASfI8AP3HP-oRDOteo/edit


** Collapsing soma into single compartment

Penny got this going, new cell is eeeS1.py.  I am renaming eeeS.py to eeeS_multi.py and renaming eeeS1.py as eeeS.py.

Commenting out the other soma trace request in cfg.py:
	#cfg.recordTraces['V_soma_0'] = {'sec':'soma_0','loc':0.5,'var':'v'}

Getting an error when I run the sim.

Found it by running netParams.py

	graham-mac:eee_net graham$ ipython -i netParams.py
	Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
	Type 'copyright', 'credits' or 'license' for more information
	IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.
	Balancing each compartment to -73 mV
	  File "../cells/eeeS.py", line 143
	    print "geom_nseg: changed from ", before, " to ", after, " total segments"
	                                   ^
	SyntaxError: Missing parentheses in call to 'print'. Did you mean print("geom_nseg: changed from ", before, " to ", after, " total segments")?

Added parentheses to print statement:

	print("geom_nseg: changed from ", before, " to ", after, " total segments")

Had to add parentheses to a bunch of print statements.

Now a new error:

	~/EEE_network/cells/eeeS.py in create_cell(self)
	    540         self.soma = h.Section(name='soma')
	    541         self.apical = [h.Section(name='apical[0]')]
	--> 542         self.basal = [h.Section(name='basal[%d]' % i) for i in xrange(10)]
	    543         self.axon = [h.Section(name='axon[0]')]
	    544 

	NameError: name 'xrange' is not defined

It seems xrange doesn't exist in Python 3.  range should do the same thing

Now it runs.  Output:

file:nb_gif/20190122_082937.png
file:nb_gif/20190122_082949.png
file:nb_gif/20190122_083017.png
file:nb_gif/20190122_083027.png
file:nb_gif/20190122_083039.png

Committing now and pushing.

** Chat with Penny and Don

	penny [11:01 PM]
	Hey Joe, the soma is collapsed into one compartment. I compared the plateau, it is consistent with the original simplified cell. I am not sure if it would cause any conflict, so I saved it in a new cell file called eeeS1.py (the class in this file is named as eeeS1).

	joe [7:53 AM]
	Awesome, thanks! I’ll try it out now.

	don [8:03 AM]
	is eeeS1 checked to joes_branch? don’t see it. sorry i’m not being much help :/

	joe [8:05 AM]
	Forget about joes_branch now (just as you were getting used to it).  :wink:  Everything is in master again now.
	Penny did a pull request and I just merged it into master.
	You’re fine Don, once we have the baseline model done we can all explore it.

	don [8:11 AM]
	ok. back to master. ty

	penny [9:00 AM]
	No worry Don, we are more familiar with the cell model. All minor changes. You can help more for the network part :slightly_smiling_face:

	don [9:10 AM]
	quick attempt to run (under eee_net) threw this error:

	NEURON: syntax error
	in FS3.hoc near line 37
	     insert Nafx
	               ^
	       xopen(“FS3.hoc”)
	     execute1(“{xopen(“FS...“)
	   load_file(“../cells/F...“)
	Segmentation fault: 11
	running under py3

	joe [9:18 AM]
	Could be one of two easy things: 1) make sure you compiled the mod files, 2) make sure `x86_64` dir is properly simlinked into `eee_net` dir.  Could also probably be a million complicated things.  :wink:

	don [9:19 AM]
	was thinking mod files while you typed ;)
	running now

	joe [9:20 AM]
	:sweat_smile:

	don [9:20 AM]
	looks good. all plots, etc showing correctly

	joe [9:21 AM]
	Awesome.  I’m off for a hike, but then I hope to get syn mechs and connectivity in today.
	That may be too ambitious.  We shall see.

	penny [9:25 AM]
	:+1:

	penny [9:51 AM]
	When I run python init.py, the figures can’t show up properly. Have u guys ever seen this before?
	No figures showing up 
	MacBook-Pro:eee_net Penny$ python init.py
	Balancing each compartment to -73 mV
	​
	Creating network of 5 cell populations on 1 hosts...
	 Number of cells on node 0: 100 
	 Done; cell creation time = 0.25 s.
	Making connections...
	 Number of connections on node 0: 1086 
	 Done; cell connection time = 0.07 s.
	Adding stims...
	 Number of stims on node 0: 100 
	 Done; cell stims creation time = 0.01 s.
	Recording 5 traces of 1 types on node 0
	​
	Running simulation for 1000 ms...
	 Done; run time = 33.19 s; real-time ratio: 0.03.
	​
	Gathering data...
	 Done; gather time = 0.19 s.
	​
	Analyzing...
	 Cells: 100
	 Connections: 1186 (11.86 per cell)
	 Spikes: 995 (9.95 Hz)
	 Simulated time: 1.0 s; 1 workers
	 Run time: 33.19 s
	 Done; saving time = 0.05 s.
	Plotting raster...
	Plotting recorded cell traces ...
	INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage10" as iconphoto: not a photo image
	INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage19" as iconphoto: not a photo image
	INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage28" as iconphoto: not a photo image
	INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage37" as iconphoto: not a photo image
	INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage46" as iconphoto: not a photo image
	Plotting 2D representation of network cell locations and connections...
	INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage55" as iconphoto: not a photo image
	Plotting connectivity matrix...
	INFO:matplotlib.backends._backend_tk:Could not load matplotlib icon: can't use "pyimage64" as iconphoto: not a photo image
	 Done; plotting time = 1.84 s
	​
	Total time = 35.61 s
	Collapse 
	I checked matplotlib, it is good. Not sure where the problem is.

	joe [9:53 AM]
	I haven’t done anything with `init.py` yet, that’s really for running batches of sims.  Right now `./runsim` should work though…

	penny [9:54 AM]
	Untitled 
	MacBook-Pro:eee_net Penny$ ./runsim
	[MacBook-Pro.local:97715] [[1500,0],0] mca_oob_tcp_recv_handler: invalid message type: 15
	[MacBook-Pro.local:97715] [[1500,0],0] mca_oob_tcp_recv_handler: invalid message type: 15
	[MacBook-Pro.local:97715] [[1500,0],0] mca_oob_tcp_recv_handler: invalid message type: 15
	[MacBook-Pro.local:97715] [[1500,0],0] mca_oob_tcp_recv_handler: invalid message type: 15
	--------------------------------------------------------------------------
	mpiexec noticed that the job aborted, but has no info as to the process
	that caused that situation.
	Collapse 
	When I do ./runsim, this error showed up. I can’t locate the problem, so tried init.py. So strange

	joe [9:55 AM]
	Hmmm.  Seems to be a problem with your MPI stuff.  Try running `./runsim 1`, which forces everything onto one core…

	penny [9:55 AM]
	Okay

	don [9:55 AM]
	i ran init.py but from python console
	ran fine
	after i compiled mods :)

	penny [9:57 AM]
	I see. Thanks. the errors are strange
	Untitled 
	MacBook-Pro:eee_net Penny$ ./runsim 1
	[MacBook-Pro.local:97848] [[1623,0],0] mca_oob_tcp_recv_handler: invalid message type: 15
	--------------------------------------------------------------------------
	mpiexec noticed that the job aborted, but has no info as to the process
	that caused that situation.

	don [9:57 AM]
	trying python init.py now

	joe [9:57 AM]
	You could post it in #tech and see if anybody else knows.  I have no idea.

	don [9:57 AM]
	windows don’t show because program exits
	no errors
	py3

	penny [9:58 AM]
	Okay. I will ask in #tech too! Thanks :slightly_smiling_face:

	joe [9:58 AM]
	Speaking of which, Don, if you could figure out how to save the figures in Netpyne (right now they don’t get saved for some reason), that would be really helpful.
	Off to a mountain for an hour.

	don [10:00 AM]
	what is 1 arg for Penny?
	when i run ./runsim 1 the windows remain blank

	penny [10:01 AM]
	Thats the number of core used

	don [10:01 AM]
	doesn’t throw an error that i can see

	penny [10:02 AM]
	sorry, number of processes

	don [10:02 AM]
	understood. ty

	penny [10:02 AM]
	Ah, when I run python -i init.py, all the figures showed up properly!
	Strange.

	don [10:03 AM]
	something about running mpi

	penny [10:05 AM]
	I guess I set up something wrong.        python init.py   --- network model runs successfully, but no figures show up;  python -i init.py    --- network  runs successfully and figures show up.
	I am guessing in the file init.py, the last part    sim.analysis.plotData()    needs to be set up with some paramters

	don [10:07 AM]
	ran:

	mpiexec -np 1 nrniv -python -mpi init.py
	numprocs=1

	got:

	There was an exception in plotConn():
	module ‘matplotlib.pyplot’ has no attribute ‘hold’

	penny [10:07 AM]
	Hmmm
	I tried the same command, but got different errors with the last plotting part. Strange.
	Going to check the netpyne documentation

	don [10:10 AM]
	you’re also using py3?

	penny [10:10 AM]
	yes

	don [10:11 AM]
	hmmm. you’re running on a mac?

	penny [10:12 AM]
	yup

	don [10:12 AM]
	argh!
	go figure …

	penny [10:13 AM]
	lol

	joe [12:44 PM]
	Did you guys get your problems sorted?

	don [12:45 PM]
	joe, it runs fine except under mpi
	i didn’t pursue mpi issue

	joe [12:45 PM]
	Penny, I realize that `./runsim` just calls `init.py` and parallelizes it.  So the first thing is to make sure you can run `init.py`.  You know, like you were trying before I said it was an mpi problem.  :joy:
	I can’t help with mpi issues.  I’m a neuroscientist in a computer scientist’s world.
	Did you have a chance to look into how to save figures, Don?

	don [12:48 PM]
	generally use cfg.analysis
	like:

	cfg.analysis[‘plotSpikeHist’] = {‘include’: [‘IT2’], ‘timeRange’: [0,1000], ‘yaxis’:‘rate’, ‘binSize’:5, ‘graphType’:‘bar’, ‘saveFig’: True, ‘showFig’: False, ‘popColors’: popColors, ‘figSize’: (10,4), ‘dpi’: 300}

	joe [12:57 PM]
	Yeah, tried to just add a saveFig option.  Didn’t work.
	Penny, if the problem is figures don’t show up for you, can you try uncommenting this line in `cfg.py`?
	#import pylab; pylab.show()  # this line is only necessary in certain systems where figures appear empty
	Hmmm.  Now figures aren’t showing up for me either.
	The problem may be this printout:
	Untitled 
	Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
	​
	Warning: Could not load cfg from command line path or from default cfg.py

** Summary of chat

Penny was having figures not show up.  Also problems with MPI.  Now my own figures aren't showing up.  It seems Netpyne is no longer reading the config file (cfg.py) properly.

I am going to commit, push, and then try the following commands as a sanity check:

cd ~ ; mkdir eee_temp ; cd eee_temp ; git clone https://github.com/Neurosim-lab/EEE_network.git ; cd EEE_network/mod ; nrnivmodl ; cd ../eee_net ; ln -s "../mod/x86_64" x86_64 ; ./runsim 1

** Chats 

	joe [1:44 PM]
	Moving a conversation here.
	I just pushed to repo.  For some reason, it’s no longer reading the config file.  Getting the same thing as the last Warning I posted.
	If you guys could update your repos and try to figure out why it’s not reading the config file, that would be helpful.
	The following one-liner should run everything (and it did until just recently):
	Untitled 
	cd ~ ; rm -rf eee_temp ; mkdir eee_temp ; cd eee_temp ; git clone https://github.com/Neurosim-lab/EEE_network.git ; cd EEE_network/mod ; nrnivmodl ; cd ../eee_net ; ln -s "../mod/x86_64" x86_64 ; ./runsim 1

	don [1:46 PM]
	running fine here joe except it throws an error on connectivity matrix

	Plotting connectivity matrix...
	There was an exception in plotConn():
	module ‘matplotlib.pyplot’ has no attribute ‘hold’
	running from py3 command

	joe [1:47 PM]
	Untitled 
	Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
	​
	Warning: Could not load cfg from command line path or from default cfg.py
	I’ve never seen that before, but Salva might know.
	Looking into why reading the config file failed…

	salvadord [1:54 PM]
	bugs in cfg.py
	run python cfg.py to see
	the last 2 lines are buggy

	joe [1:57 PM]
	Thanks.  Just figured out cfg crashed.  Everything is obvious in hindsight.  :joy:

** Fixing problems

So the problem was that running cfg.py caused a crash.  Fixed that problem. Sloppy coding. 

I believe it works now.  Pushing now to try.  After, the following should work:

	cd ~ ; rm -rf eee_temp ; mkdir eee_temp ; cd eee_temp ; git clone https://github.com/Neurosim-lab/EEE_network.git ; cd EEE_network/mod ; nrnivmodl ; cd ../eee_net ; ln -s "../mod/x86_64" x86_64 ; ./runsim 1

It does work now.  Asking others to try.

	salvadord [1:54 PM]
	bugs in cfg.py
	run python cfg.py to see
	the last 2 lines are buggy

	joe [1:57 PM]
	Thanks.  Just figured out cfg crashed.  Everything is obvious in hindsight.  :joy:

	joe [2:11 PM]
	Okay, fixed problem in cfg.py, and now everything seems to work.  Added `showFig` and `saveFig` options in cfg.py.  Committed and pushed.  I would appreciate if people would run the following one-liner and let me know if it crashes:
	Untitled 
	cd ~ ; rm -rf eee_temp ; mkdir eee_temp ; cd eee_temp ; git clone https://github.com/Neurosim-lab/EEE_network.git ; cd EEE_network/mod ; nrnivmodl ; cd ../eee_net ; ln -s "../mod/x86_64" x86_64 ; ./runsim
	Penny, let us know if you’re still getting MPI issues, and we’ll try to solve them.

	The one-liner should both display figures and save figures to: `~/eee_temp/EEE_network/eee_net`

	salvadord [2:16 PM]
	one-liner works for me! :woman-with-bunny-ears-partying:

	billl [2:17 PM]
	remind from whence to clone

	salvadord [2:17 PM]
	one-liner above does everything, including clone

	billl [2:18 PM]
	oh

	joe [2:28 PM]
	Don, let us know if you still get that plotConn error with the one-liner.  No hurry.
	Salva, would it be useful to have a Netpyne “pre-checker” that throws an error if either netParams.py or cfg.py crashes during loading?  I’d be happy to put a ticket in (and even work on it in my spare time), but I’m not sure if that’s worthwhile.

	salvadord [2:33 PM]
	what would be difference with warning msg you got above?

	billl [2:33 PM]
	failed; supposed to run with 3 or 2?

	joe [2:36 PM]
	Salva: it didn’t throw an error, just a non-specific warning.  It’s just I’ve had this problem before, and it would immediately remind me to check and make sure both netParams.py and cfg.py don’t throw an error.
	Bill: 3

	billl [2:36 PM]
	maybe need to build py3 into runsim?

	joe [2:37 PM]
	I have switched to Python 3 completely.  Finally.  I wouldn’t know how to include a Python version choice in runsim… but I’m open to suggestions.

	billl [2:38 PM]
	call it python3 typically

	salvadord [2:39 PM]
	joe: the warning is result of error loading cfg.py so maybe can just change warning msg to make clearer and/or stop execution — but sure feel free to open gituhb issue and work on it if have time… Im sure helpful

	joe [2:39 PM]
	The active line in runsim is: `mpiexec -np $numprocesses nrniv -python -mpi init.py $@  # Run the model`

	billl [2:39 PM]
	nrniv generally deprecated
	get this error now  `/usr/bin/python3: No module named pi`

	salvadord [2:40 PM]
	can you run with mpi calling python instead of nrniv?

	joe [2:40 PM]
	I would love to try.  How would you change the active line to make that happen?

	salvadord [2:41 PM]
	oh Im asking if possible :slightly_smiling_face:

	ramcdougal [2:41 PM]
	normally yes

	billl [2:41 PM]
	this maybe?  mpiexec -np $numprocesses python3 -mpi init.py $@  # Run the model

	ramcdougal [2:41 PM]
	not sure if something weird about this model
	drop the -mpi
	that tells it to run a module called mpi
	errr
	called pi

	billl [2:41 PM]
	oh ic

	ramcdougal [2:42 PM]
	e.g. python -m CGIHTTPServer launches a server
	in py2
	but yeah

	billl [2:42 PM]
	so how to run with python with mpi?

	ramcdougal [2:42 PM]
	no need for the -mpi
	as long as you have
	a `from mpi4py import MPI` before you import NEURON
	in super recent versions of NEURON, there's also a parallelcontext solution that removes the need for the `mpi4py` module...

	billl [2:43 PM]
	ic -- so would need to include in the init joe

	joe [2:46 PM]
	Untitled 
	 File "init.py", line 17, in <module>
	  from mpi4py import MPI
	ModuleNotFoundError: No module named 'mpi4py'

Error:

Traceback (most recent call last):
  File "init.py", line 17, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'

pip install mpi4py

	graham-mac:EEE_network graham$ pip install mpi4py
	Collecting mpi4py
	  Downloading https://files.pythonhosted.org/packages/31/27/1288918ac230cc9abc0da17d84d66f3db477757d90b3d6b070d709391a15/mpi4py-3.0.0.tar.gz (1.4MB)
	    100% |████████████████████████████████| 1.4MB 6.3MB/s 
	Building wheels for collected packages: mpi4py
	  Running setup.py bdist_wheel for mpi4py ... done
	  Stored in directory: /Users/graham/Library/Caches/pip/wheels/23/03/c5/30289417f1428c692651e046174b64ac871a377df227802bf6
	Successfully built mpi4py
	Installing collected packages: mpi4py
	Successfully installed mpi4py-3.0.0

Now it runs.  Committing, pushing, asking others to run one-liner.

Whoops, actually changed the old runsim.  Reverting that, changing new one, and trying again.

Hmm.  Four processes and four of each figure.

	joe [2:56 PM]
	Hmmm.  Changing to remove -mpi and importing mpi4py made things wonky…  Running on four cores and got four of each figure…

	billl [2:56 PM]
	ok well if i'm only 1 with a problem let's ot worry on this
	i'll fix for myself

	joe [2:56 PM]
	:+1: Sweet.  Moving on.

Switching back, and everything works as expected.

Will commit, test one-liner, and then move on to swapping in our synaptic mechs.

One-liner worked.  Moving on.


* 2019-01-23 -- Synaptic mechanisms

In progress
-----------
Setting up network model
Set up synaptic mechanisms
Set initial connectivity to Sergio's settings


** Setting up synaptic mechanisms

Want to swap in our synaptic mechanisms for the generic Exp2Syns from the tutorial.

Code from old model:

	# MyExp2syn synaptic mechanisms
	netParams.synMechParams['GABAAfast'] = {'mod':'MyExp2SynBB','tau1':0.07,'tau2':18.2,'e': cfg.GABAAfast_e}
	netParams.synMechParams['GABAAslow'] = {'mod': 'MyExp2SynBB','tau1': 10, 'tau2': 200, 'e': cfg.GABAAslow_e}

	# DMS synaptic mechanisms 
	netParams.synMechParams['NMDA'] = {'mod': 'NMDAeee', 'Cdur': cfg.CdurNMDAScale * 1.0, 'Alpha': cfg.NMDAAlphaScale * 4.0, 'Beta': cfg.NMDABetaScale * 0.0015, 'gmax': cfg.NMDAgmax, 'e': cfg.eNMDA}
	netParams.synMechParams['AMPA'] = {'mod': 'AMPA', 'gmax': cfg.ratioAMPANMDA * cfg.NMDAgmax}

	ESynMech = ['AMPA','NMDA']
	ISynMech = ['GABAAfast','GABAAslow']

Code from tutorial:

	## Synaptic mechanism parameters
	netParams.synMechParams['exc'] = {'mod': 'Exp2Syn', 'tau1': 0.8, 'tau2': 5.3, 'e': 0}  # NMDA synaptic mechanism
	netParams.synMechParams['inh'] = {'mod': 'Exp2Syn', 'tau1': 0.6, 'tau2': 8.5, 'e': -75}  # GABA synaptic mechanism

Will need to add some parameters to the config file (or decide to hardcode them):

	Parameter 				cfg.py value            mod value
	=================       ==================      ============
	cfg.GABAAfast_e          -80.0                   0.0
	cfg.GABAAslow_e          -90.0                   0.0
	cfg.CdurNMDAScale          1.0                   1.0
	cfg.NMDAAlphaScale         1.0 (*4.0)            4.0
	cfg.NMDABetaScale         14.0                   0.0015
	cfg.NMDAgmax               0.01                  1.0
	cfg.eNMDA                -10.0                   0.0
	cfg.ratioAMPANMDA          4.0                   n/a

First, should make sure these parameters don't change the values that Penny uses in the detailed model.

Detailed model here:
https://github.com/super-penguin/EEE_Detailed_Cell

	Parameter 				Detailed model
	=================       ==================
	cfg.CdurNMDAScale        
	cfg.NMDAAlphaScale         
	cfg.NMDABetaScale         
	cfg.NMDAgmax               
	cfg.eNMDA                
	cfg.ratioAMPANMDA          

Actually, first I want to see which NMDA mod files are used in the detailed model:

The DMS model uses:   h.NMDA     
	from mod file :  NMDA.mod
	https://github.com/super-penguin/EEE_Detailed_Cell/blob/master/mod/NMDA.mod
With values set to:
    SynNMDA[-1].gmax = 0.005
    SynNMDA[-1].Beta = Beta
    SynNMDA[-1].Cdur = Cdur

The Major model uses:  h.nmda     
	from mod file   : NMDAmajor.mod
	https://github.com/super-penguin/EEE_Detailed_Cell/blob/master/mod/NMDAmajor.mod
With values set to:
    tempNMDA.gmax = 0.005 * Syn_w1

Hmmm.  So it seems that Penny's model uses a different NMDA mod file than we are (NMDA.mod --> NMDA, while we use NMDAeee.mod --> NMDAeee)

I'll have to run a diff.  Or just switch to Penny's mod file...

Hmmmm.  No sense in running a diff.  I'll ask in Slack which mod we want to start using for the network model.  


* 2019-01-25 -- Synaptic mechs and connectivity 

In progress
-----------
Setting up network model
Set up synaptic mechanisms
Set initial connectivity to Sergio's settings


** Setting up synaptic mechanisms

Asking about which NMDA mod to use:

	joe [9:37 AM]
	It’s easy enough to swap them out, but I’m wondering which of the detailed model’s NMDA mod files we should start using for the network model, the DMS or the Major?

	billl [9:38 AM]
	DMS since faster
	but if you have any reason for a major Major or a minor Major preference then can do that

So the DMS model is NMDA.mod.  I notice we already have an NMDA.mod in the network mod dir.  I'm going to compare with Penny's.

Penny's:
https://github.com/super-penguin/EEE_Detailed_Cell/blob/master/mod/NMDA.mod

Network:
https://github.com/Neurosim-lab/EEE_network/blob/master/mod/NMDA.mod

Diff using Sublime:

	--- /Users/graham/Desktop/NMDAdiff/NMDA_net.mod	Fri Jan 25 10:08:57 2019
	+++ /Users/graham/Desktop/NMDAdiff/NMDA_penny.mod	Fri Jan 25 10:09:26 2019
	@@ -81,7 +81,7 @@
	 	Cmax	= 1	 (mM)           : max transmitter concentration
	 	Cdur	= 1	 (ms)		: transmitter duration (rising phase)
	 	Alpha	= 4 (/ms /mM)	: forward (binding) rate (4)
	-	Beta 	=0.01   (/ms)
	+	Beta 	=0.01   (/ms)   : backward (unbinding) rate
	 	e	= 0	 (mV)		: reversal potential
	     mg   = 1      (mM)           : external magnesium concentration
	 	gmax = 1   (uS)

No significant differences, but I'll replace the network NMDA.mod with Penny's just so they're identical.

I see the network mod dir doesn't have Penny's NMDAmajor.mod:
https://github.com/super-penguin/EEE_Detailed_Cell/blob/master/mod/NMDAmajor.mod

I'll add it to the network mod dir.

Don't know what this means, but adding here just in case it becomes a problem:

	graham-mac:EEE_network graham$ git add mod/NMDAmajor.mod 
	warning: CRLF will be replaced by LF in mod/NMDAmajor.mod.
	The file will have its original line endings in your working directory.

Here's the current network NMDA settings:

	netParams.synMechParams['NMDA'] = {'mod': 'NMDAeee', 'Cdur': cfg.CdurNMDAScale * 1.0, 'Alpha': cfg.NMDAAlphaScale * 4.0, 'Beta': cfg.NMDABetaScale * 0.0015, 'gmax': cfg.NMDAgmax, 'e': cfg.eNMDA}

Need to change it to use NDMA.mod, and ensure the parameter values are the same as Penny's.

Here's how she sets up her NMDA:

    #Adding NMDA
    SynNMDA.append(h.NMDA(Cell.basal[34](loc1[i])))
    SynNMDA[-1].gmax = 0.005
    SynNMDA[-1].Beta = Beta
    SynNMDA[-1].Cdur = Cdur
    nc_NMDA.append(h.NetCon(ns, SynNMDA[i]))
    nc_NMDA[-1].delay = delay1[i]
    nc_NMDA[-1].weight[0] = Syn_w1

Here's the function she uses to run sims for figure 3:

	def Glu_Stim(TTX = False, Pool1_num = 9, Pool2_num = 9, Beta = 0.067,
	Cdur = 1, Syn_w1 = 0.01, Syn_w2 = 0.01, Loc = [0.2, 0.6]):

And here's how she calls that function for the figure 3 simulations
https://github.com/super-penguin/EEE_Detailed_Cell/blob/master/Fig3_exp_dms.py

    loc = [0.25, 0.6]
    weight = [0.1, 0.15, 0.20, 0.25, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

    for w in weight:
        Pool_num = 8 + int(20*w)
        Glu_Stim(False, Pool_num, Pool_num, 0.02, 50 + int(100*w), w, w, loc)

There are a couple things I find odd here...  

1) the number of synapses (Pool_num) is a function of the weight of glutamate stim instead of a constant
2) Cdur is also a function of weight
3) default Beta is 0.067, but the call uses 0.02

I'm going to look into how she runs sims for figure 5:
https://github.com/super-penguin/EEE_Detailed_Cell/blob/master/Fig5_exp_DMS.py

Here's her function:

	def Glu_Stim(Bnum = 34, TTX = False, Pool1_num = 9, Pool2_num = 9,
	Beta = 0.067, Cdur = 1, Syn_w1 = 0.01, Syn_w2 = 0.01, Loc = [0.2, 0.6], DenLoc = 0.5):

Here's how she calls it:

    Pool_num = 12
    weight = [0.7, 0.9] # 0.7 for Fig 5. B1, 0.9 for Fig D1

    basal_num = [15, 34, 14, 22, 25, 31]
    with open('data.json', 'r') as fp:
        data = json.load(fp)
    with open('dend_measure_data.json', 'r') as fp1:
        Ndata = json.load(fp1)

    for b in basal_num:
        loc = data[str(b)]
        DenLoc = Ndata[str(b)]
        for l1, l2 in zip(loc, DenLoc):
            for w in weight:
                Glu_Stim(b, False, Pool_num, Pool_num, 0.02, 10, w, w, l1, l2)
                Glu_Stim(b, True, Pool_num, Pool_num, 0.02, 10, w, w, l1, l2)

Okay, so here anyway, Pool_num is a constant (12) and Cdur is a constant (10).

Beta is set to 0.02 (though 0.067 is the default).  Looking into the values of Beta and Cdur in the NMDA.mod file.

Beta is 0.01 in NMDA.mod
Cdur is 1 in NMDA.mod

I should bring these oddities up with Penny et al.

One other thing: she uses a 1:1 NMDA:AMPA weight ratio...  We had always used an AMPA/NMDA ratio.

Actually, that was to adjust gmax for NMDA and AMPA.  Looking into NMDA and AMPA gmax in the detailed model...

	SynAMPA[-1].gmax = 0.05
	SynNMDA[-1].gmax = 0.005

So Penny uses a NMDA/AMPA ratio of 0.1 for gmax.

Need to set gmax for NMDA and AMPA in network model.

Added to top of netParams:

	## Network variables (move to cfg.py later)
	NMDAgmax        = 0.005
	NMDA2AMPA       = 0.1
	AMPAgmax        = NMDAgmax / NMDA2AMPA
	NMDAweight      = 0.8
	AMPAweight      = NMDAweight

And then below changed to:

	## Excitatory NMDA and AMPA synaptic mechs
	netParams.synMechParams['NMDA'] = {'mod': 'NMDA', 'Cdur': 10.0, 'Beta': 0.02, 'gmax': NMDAgmax}
	netParams.synMechParams['AMPA'] = {'mod': 'AMPA', 'gmax': AMPAgmax}

I think we'll need to test the network implementation of simplified cell model to ensure it behaves like detailed.


** Back to setting up NMDA mech

Previous code:

	netParams.synMechParams['NMDA'] = {'mod': 'NMDAeee', 'Cdur': cfg.CdurNMDAScale * 1.0, 'Alpha': cfg.NMDAAlphaScale * 4.0, 'Beta': cfg.NMDABetaScale * 0.0015, 'gmax': cfg.NMDAgmax, 'e': cfg.eNMDA}

New code:

	netParams.synMechParams['NMDA'] = {'mod': 'NMDA', 'Cdur': 10.0, 'Beta': 0.02, 'gmax': NMDAgmax}


** Setting up inhibitory mechs

The old code actually stays the same:

	## Inhibitory GABA synaptic mechs
	netParams.synMechParams['GABAAfast'] = {'mod':'MyExp2SynBB','tau1': 0.07,'tau2': 18.2,'e': cfg.GABAAfast_e}
	netParams.synMechParams['GABAAslow'] = {'mod': 'MyExp2SynBB','tau1': 10, 'tau2': 200, 'e': cfg.GABAAslow_e}


** Looking into connectivity

Now we need to make sure our connectivity is using the newly swapped in mechs.

Old code in netParams:

	## Cell connectivity rules
	netParams.connParams['PT5->all'] = {
	  'preConds': {'cellType': 'PT5'}, 'postConds': {'y': [100,1000]},  #  E -> all (100-1000 um)
	  'probability': 0.1 ,                  # probability of connection
	  'weight': '0.005*post_ynorm',         # synaptic weight 
	  'delay': 'dist_3D/propVelocity',      # transmission delay (ms) 
	  'synMech': 'exc'}                     # synaptic mechanism 

	netParams.connParams['PV5->PT5'] = {
	  'preConds': {'cellType': 'PV5'}, 'postConds': {'cellType': ['PT5']},       #  I -> E
	  'probability': '0.4*exp(-dist_3D/probLengthConst)',   # probability of connection
	  'weight': 0.001,                                      # synaptic weight 
	  'delay': 'dist_3D/propVelocity',                      # transmission delay (ms) 
	  'synMech': 'inh'}     

New code:

	## Cell connectivity rules
	netParams.connParams['PT5->all'] = {
	  'preConds': {'cellType': 'PT5'},
	  'postConds': {'cellType': ['PT5','PV5']},
	  'probability': 0.1,
	  'weight': [NMDAweight, AMPAweight],
	  'delay': 'dist_3D/propVelocity',
	  'synMech': 'ESynMech'}

	netParams.connParams['PV5->all'] = {
	  'preConds': {'cellType': 'PV5'},
	  'postConds': {'cellType': ['PT5', 'PV5']},
	  'probability': 0.1,
	  'weight': [GABAAfastWeight, GABAAslowWeight],
	  'delay': 'dist_3D/propVelocity',
	  'synMech': 'ISynMech'} 

Now need to set weights for GABAA fast and slow.

Looking into how the old network model did it.

Hmmm.  Interesting.  So the connectivity is such that for inh to exc, both GABA fast and slow are used.  For inh to inh, only GABA fast is used.

Old code:

	#     #inh to exc 
	#     for prePop in inhL5:
	#         for postPop in excL5:
	#             ruleLabel = prePop+'->'+postPop
	#             netParams.connParams[ruleLabel] = {
	#                 'preConds': {'pop': prePop},
	#                 'postConds': {'pop': postPop},
	#                 'synMech': ISynMech, 
	#                 'weight': 0.001*cfg.IEgain, 
	#                 'synMechWeightFactor': [0.7,0.3],
	#                 'delay': 'defaultDelay+dist_3D/propVelocity',
	#                 'convergence': 4,
	#                 'loc': 0.5,
	#                 'sec': 'soma_2'}
	  
	#     #inh to inh
	#     for prePop in inhL5:
	#         for postPop in inhL5:
	#             ruleLabel = prePop+'->'+postPop
	#             netParams.connParams[ruleLabel] = {
	#                 'preConds': {'pop': prePop},
	#                 'postConds': {'pop': postPop},
	#                 'synMech': 'GABAAfast',
	#                 'weight': 0.002*cfg.IIgain, 
	#                 'delay': cfg.IIdelay, #'defaultDelay+dist_3D/propVelocity',
	#                 'convergence': cfg.IIconv,
	#                 'loc': 0.5,
	#                 'sec': 'soma'}

Where:

	cfg.IEgain = 0.1 #10.0 #0.5    #PV to Exc 
	cfg.IIgain = 0.1 #1.0 #1.0 # PV to PV

So, the weight for I->E = 0.001*cfg.IEgain = 0.001*0.1 = 0.0001

The weight is the same for GABA fast and slow.

And the weight for I->I = 0.002*cfg.IIgain = 0.002*0.1 = 0.0002

Which is the weight for just GABA fast, as that is all that's used.

I'm going to set up the new connectivity in the same way and also ask about it in Slack.


** Setting up connectivity

New code:

	## Cell connectivity rules
	netParams.connParams['PT5->all'] = {
	  'preConds': {'cellType': 'PT5'},
	  'postConds': {'cellType': ['PT5','PV5']},
	  'probability': 0.1,
	  'weight': [NMDAweight, AMPAweight],
	  'delay': 'dist_3D/propVelocity',
	  'synMech': 'ESynMech'}

	netParams.connParams['PV5->PT5'] = {
	  'preConds': {'cellType': 'PV5'},
	  'postConds': {'cellType': 'PT5'},
	  'probability': 0.1,
	  'weight': [GABAAfastWeight, GABAAslowWeight],
	  'delay': 'dist_3D/propVelocity',
	  'synMech': 'ISynMech'} 

	netParams.connParams['PV5->PV5'] = {
	  'preConds': {'cellType': 'PV5'},
	  'postConds': {'cellType': 'PV5'},
	  'probability': 0.5,
	  'weight': GABAAfastWeight,
	  'delay': 'dist_3D/propVelocity',
	  'synMech': 'GABAAfast'} 

Okay, enough changing.  Time to make it run.

Committing first.

** Running the sim


* 2019-01-28 -- Synaptic mechs and connectivity 

In progress
-----------
Setting up network model
Set up synaptic mechanisms
Set initial connectivity to Sergio's settings


** Running the sim to see what's broken

Trial run:

	graham$ cd ~/EEE_network/eee_net ; ./runsim
	...
	Warning: Could not load netParams from command line path or from default netParams.py
	...

No dice.  Probably a problem in netParams.py

	graham-mac:EEE_network graham$ cd ~/EEE_network/eee_net
	graham-mac:eee_net graham$ ipython -i netParams.py
	Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
	Type 'copyright', 'credits' or 'license' for more information
	IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.
	Balancing each compartment to -73 mV
	---------------------------------------------------------------------------
	NameError                                 Traceback (most recent call last)
	~/EEE_network/eee_net/netParams.py in <module>
	     63 
	     64 ## Inhibitory GABA synaptic mechs
	---> 65 netParams.synMechParams['GABAAfast'] = {'mod':'MyExp2SynBB','tau1': 0.07,'tau2': 18.2,'e': cfg.GABAAfast_e}
	     66 netParams.synMechParams['GABAAslow'] = {'mod': 'MyExp2SynBB','tau1': 10, 'tau2': 200, 'e': cfg.GABAAslow_e}
	     67 

	NameError: name 'cfg' is not defined

Or perhaps a problem in cfg.py.  Nope.  cfg.py runs without crashing.

Adding the following to the top of netParams.py (it was in the old netParams):

	try:
	    from __main__ import cfg
	except:
	    from cfg import cfg

And executing netParams:

	AttributeError                            Traceback (most recent call last)
	~/EEE_network/eee_net/netParams.py in <module>
	     67 
	     68 ## Inhibitory GABA synaptic mechs
	---> 69 netParams.synMechParams['GABAAfast'] = {'mod':'MyExp2SynBB','tau1': 0.07,'tau2': 18.2,'e': cfg.GABAAfast_e}
	     70 netParams.synMechParams['GABAAslow'] = {'mod': 'MyExp2SynBB','tau1': 10, 'tau2': 200, 'e': cfg.GABAAslow_e}
	     71 

	AttributeError: 'SimConfig' object has no attribute 'GABAAfast_e'

Will add "cfg." in front of all variables, will later move these to cfg.py.

Okay, netParams.py runs now.

Now to try a whole sim.

Getting an error:

	graham$ cd ~/EEE_network/eee_net ; ipython -i init.py
	Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
	Type 'copyright', 'credits' or 'license' for more information
	IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.
	Note: NeuroML import failed; import/export functions for NeuroML will not be available. 
	  To install the pyNeuroML & libNeuroML Python packages visit: https://www.neuroml.org/getneuroml
	Balancing each compartment to -73 mV

	Creating network of 5 cell populations on 1 hosts...
	  Number of cells on node 0: 100 
	  Done; cell creation time = 0.30 s.
	Making connections...
	---------------------------------------------------------------------------
	TypeError                                 Traceback (most recent call last)
	~/EEE_network/eee_net/init.py in <module>
	     22 sim.net.createPops()                        # instantiate network populations
	     23 sim.net.createCells()                       # instantiate network cells based on defined populations
	---> 24 sim.net.connectCells()                      # create connections between cells based on params
	     25 sim.net.addStims()                          # add network stimulation
	     26 sim.setupRecording()                       # setup variables to record for each cell (spikes, V traces, etc)

	~/Applications/netpyne/netpyne/network/conn.py in connectCells(self)
	     76                                 sim.cfg.seeds['conn'])
	     77             self._connStrToFunc(preCellsTags, postCellsTags, connParam)  # convert strings to functions (for the delay, and probability params)
	---> 78             connFunc(preCellsTags, postCellsTags, connParam)  # call specific conn function
	     79 
	     80         # check if gap junctions in any of the conn rules

	~/Applications/netpyne/netpyne/network/conn.py in probConn(self, preCellsTags, postCellsTags, connParam)
	    402                                 connParam[paramStrFunc + 'Args'][funcKey] = connParam[paramStrFunc + 'Vars'][funcKey](preCellTags, postCellTags)
	    403                             # connParam[paramStrFunc+'Args'] = {k:v if isinstance(v, Number) else v(preCellTags,postCellTags) for k,v in connParam[paramStrFunc+'Vars'].items()}
	--> 404                         self._addCellConn(connParam, preCellGid, postCellGid) # add connection
	    405 
	    406 

	~/Applications/netpyne/netpyne/network/conn.py in _addCellConn(self, connParam, preCellGid, postCellGid)
	    610         if sim.cfg.includeParamsLabel: params['label'] = connParam.get('label')
	    611 
	--> 612         postCell.addConn(params=params)
	    613 
	    614 

	~/Applications/netpyne/netpyne/cell/compartCell.py in addConn(self, params, netStimParams)
	    740                     else:
	    741                         sec = self.secs[synMechSecs[i]]
	--> 742                         postTarget = synMechs[i]['hObj'] # local synaptic mechanism
	    743 
	    744                     if netStimParams:

	TypeError: 'NoneType' object is not subscriptable

So the crash occurs during `sim.net.connectCells()`, which implies a problem with connectivity.

It seems like `synMechs` is undefined, and thus not subscriptable.  Looking into this.

In the connectivity section of netParams, I had this:
	'synMech': 'ESynMech'

But I think it should be this:
	'synMech': ESynMech

Same for ISynMech.

Same error.

For the background input, I have the following:
	
	netParams.stimTargetParams['bkg->all'] = {'source': 'bkg', 'conds': {'cellType': ['PV5','PT5']}, 'weight': 0.01, 'delay': 'max(1, normal(5,2))', 'synMech': 'exc'}

But I realize I no longer have a synMech named 'exc'...  Looking into what 'exc' used to be...

From the Netpyne tutorial (http://netpyne.org/tutorial.html):

	netParams.synMechParams['exc'] = {'mod': 'Exp2Syn', 'tau1': 0.8, 'tau2': 5.3, 'e': 0}  # NMDA synaptic mechanism

Based on the comment, it's supposed to be an NMDA model, so I suppose I could use the NMDA.mod, but I'm just going to keep it the same for now.

It runs and produces figures.  :)

But the connectivity is a little wonky:
file:nb_gif/20190128_102730.png

Both `PV5` and `bkg` seem to have no connectivity.

Committing, pushing, and then looking into this.


** Fixing connectivity

Earlier I had increased the connection probability from 0.1 to 0.5, gonna try changing that back and seeing what happens.

Still missing connectivity, but the plots look much better.

Instead of lumping synMechs into excitatory and inhibitory:

	## Synaptic mechanism parameters
	ESynMech = ['NMDA','AMPA']
	ISynMech = ['GABAAfast','GABAAslow']

I'll set each connection type up separately.

	NMDA
	AMPA
	GABAAFast
	GABAASlow
	bkg


* 2019-01-29 -- EEE meeting and connectivity 

In progress
-----------
Setting up network model
Fixing connectivity


** EEE Meeting

https://docs.google.com/document/d/16vmQn6gmJzhUXq48PAuTd9uzx5keSdxT0qSn3yWfC9g/edit

Get connectivity fixed and then start setting up batch sims.


** Connectivity

Salva was looking into the problem.

	salvadord [9:17 AM]
	so all the conns are actually there!

	billl [9:18 AM]
	that's the good news

	salvadord [9:18 AM]
	for the PV5 if you plot eg. the probability instead of the strength you can see them
	strength=prob*weight

	billl [9:18 AM]
	maybe the strength == 0?

	salvadord [9:18 AM]
	so seems like PV5 weights are much lower
	just lower by several O - 0.0001 vs 0.8

	billl [9:19 AM]
	goose 'em joe

	salvadord [9:19 AM]
	and the bkg also there but since implemented as a stimSourceParam/stimTargetParam (it’s a NetStim) the conn matrix calculation doesnt really apply
	there’s one netstim per cell

	joe [9:20 AM]
	Awesome, thanks Salva!

	salvadord [9:20 AM]
	np!

	you can plot without bkg using `sim.analysis.plotConn(includePre=['allCells'], includePost=['allCells'], feature='probability')` — and can replace `probability` with `strength`, `weight` or `numConns`


** Preparing for batch sims

Ugh, sick as a dog.  This will have to wait.


* 2019-01-30 -- Reading journal club article

Cortical column and whole-brain
imaging with molecular contrast
and nanoscale resolution

https://paperpile.com/view/3070709c-e7e3-0e02-ad60-cf7cb111d3a4

Journal club was moved to Monday Feb 11th, 12pm EST.


* 2019-02-05 -- EEE meeting and connectivity 

In progress
-----------
Setting up network model
Fixing connectivity
Setting up batch sims


** Connectivity

So the connectivity actually works, some of it is just at very low values.

Best way to explore connectivity is using batch sims.

In order to start using batch sims, first I need to get all cfg.values into the cfg.py file.

Doing that now.









