#!/bin/bash 
#SBATCH --job-name=eee_net_03-25-2019_03
#SBATCH -A shs100
#SBATCH -t 0:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=10
#SBATCH -o eee_net_03-25-2019_03.run
#SBATCH -e eee_net_03-25-2019_03.err
#SBATCH --mail-user=joe.w.graham@gmail.com
#SBATCH --mail-type=end
source ~/.bashrc
cd /home/jwgraham/EEE_network/eee_net/
ibrun -np 4 nrniv -python -mpi init.py
