#!/bin/bash 
#SBATCH --job-name=eee_net_20190401_batch
#SBATCH -A shs100
#SBATCH -t 0:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH -o eee_net_20190401_batch.run
#SBATCH -e eee_net_20190401_batch.err
#SBATCH --mail-user=joe.w.graham@gmail.com
#SBATCH --mail-type=end
source ~/.bashrc
cd /home/jwgraham/EEE_network/eee_net/
ibrun -np 4 nrniv -python -mpi batch.py